export const COLOURS={
    white: "#ffffff",
    black: "#000000",
    green: "#00AC76",
    red: "#C04345",
    blue: "#0043F9",
    backgroundLight: "#F0F0F3",
    backgroundMedium: "#B9B9B9",
    backgroundDark: "#777777",
}

export const Items =[
    {
        id: 1,
        category: "product",
        productName: "Konami Baraja de inicio del juego de cartas coleccionables YuGiOh: Codebreaker",
        productPrice: 11,
        description: "Codebreaker presenta los conceptos básicos de Dueling con cartas que son fuertes y fáciles de entender. Los nuevos duelistas pueden aprender los conceptos básicos de la invocación de enlaces usando monstruos de enlace Code Talker, luego usar este mazo de inicio como base para construir su propio Deck único recolectando monstruos Cyberse y monstruos de enlace Code Talker de muchos lanzamientos diferentes, incluyendo Structure Deck: Cyberse Link y Extreme Force.",
        isOff:true,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/productos1.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/productos1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
     {
        id: 12,
        category: "product",
        productName: "Yu-Gi-Oh! TCG: Oro máximo - El Dorado",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto13.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto13.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 2,
        category: "product",
        productName: "YU-GI-OH! Estructura de la cubierta: Albaz Strike",
        productPrice: 17,
        description: " Esta Baraja de Estructura está construida alrededor del poderoso efecto de Invocación de Fusión de Caído de Albaz que le permite absorber monstruos enemigos en sí mismo para transformarse e incluye múltiples formas nuevas de Fusión para expandir aún más su poder.",
        isOff:false,
        ofPorcentage:5,
        productImage: require("../dataBase/images/products/producto3.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto3.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 3,
        category: "product",
        productName: "Yu-Gi-Oh! Trading Cards Cyber Strike Structure Deck, Multicolor",
        productPrice: 20,
        description: " Este es uno de los mazos de estructura más personalizables hasta ahora. Puedes elegir centrarte en la estrategia original de Cyber Dragon Fusion de Zane, su estrategia Cyberdark basada en Dragones, o jugar ambos juntos en un solo Deck como en las últimas temporadas de Yu-Gi-Oh! GX. ¡Ciberdragones! ¡Puedes fusionar varias copias de Cyber Dragon con Power Bond para crear la firma Cyber End Dragon de Zane y elevar su ATK hasta 8000! Es más fácil que nunca gracias a un nuevo monstruo que puede agregar Power Bond desde tu Deck y permitirte usar monstruos en tu Cementerio como Materiales de Fusión para ello. ¡Cyberdarks! Carga tu cementerio con dragones, luego equiparlos a tus monstruos Cyberdark para encenderlos. ",
        isOff:false,
        ofPorcentage:9,
        productImage: require("../dataBase/images/products/producto4.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto4.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 4,
        category: "product",
        productName: "Yu-Gi-Oh! TCG: La cubierta de estructura del Rey Carmesí",
        productPrice: 15,
        description: "Pesada es la cabeza que lleva la corona, a menos que seas Jack Atlas, el Maestro de Más Rápido La nueva cubierta de estructura con Jack Atlas te pone en el asiento del conductor del Torbellino de Fénix y te da el control de las muchas caras del Dragón Rojo Archidiendo. Empieza por Sincronía Invocando a uno de los monstruos Archifiendo Dragón Rojo de Nivel 8, luego Invoca de Modo Especial más monstruos Resonadores hasta que tengas la combinación correcta para desatar incluso monstruos de sincronismo de nivel superior como el imperioso Dragón Nova Rojo. Esta cubierta de estructura incluye una cubierta extra masiva para maximizar su flexibilidad estratégica. También incluye un nuevo Monstruo de Sincronía de Nivel 8 que cuenta como Arquidiendo Dragón Rojo en el campo o en el Cementerio y puede turboalimentar tu propia estrategia mientras envía a tu oponente de vuelta a la edad de piedra de los duelos. ",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto5.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto5.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 5,
        category: "product",
        productName: "TCG: La leyenda de las bestias de cristal estructura cubierta",
        productPrice: 18,
        description: "¡Redescubre el poder de los lazos familiares con Structure Deck: Legend of the Crystal Beasts*! Esta Baraja de Estructura ofrece un tema querido del Yu-Gi-Oh! GX serie animada un nuevo brillo! Originalmente debutando en Force of the Breaker, las Bestias de Cristal de Jesse Anderson están de vuelta a lo grande con muchas cartas nuevas, incluida una nueva forma de Dragón Arco Iris como un Monstruo de Fusión que puede alcanzar 11000 ATK, despejar el campo y liberar a tus monstruos desterrados Bestia de Cristal para un golpe final devastador.",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto6.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto6.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 6,
        category: "product",
        productName: "Yu-Gi-Oh! Trading Cards Tarjetas: Dios egipcio SLIFER Deck, Multicolor",
        productPrice: 15,
        description: "¡Despierta el poder de las cartas de dios egipcios! Si alguna vez has querido construir un Deck alrededor de una carta de Dios Egipcio pero no sabías por dónde empezar, no busques más allá de las Barajas de Dios Egipcio! Baraja de Dios Egipcio: Sl ifer el Dragón del Cielo y la Cubierta de Dios Egipcio: Obelisco el Tormentador sirven estrategias simples para Invocar y ganar con Slifer el Dragón del Cielo u Obelisco el Tormentador. Slifer the Sky DragonSlifer se enciende dependiendo de cuántas cartas tengas en tu mano, por lo que este Deck utiliza efectos generadores de tokens para ayudarte a reunir los 3 Tributos requeridos mientras usas menos cartas de tu mano.",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto7.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto7.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 7,
        category: "product",
        productName: "Yu-Gi-Oh! Trading Cards Cubierta Obelisco de Dios Egipcio, Multicolor",
        productPrice: 11,
        description: "Obelisco el TormentorLibera el verdadero poder del Obelisco el Tormentador tributando 2 monstruos que controlas y borra los monstruos de tu oponente del campo! Este Deck utiliza monstruos autorreplicantes para proporcionar tributos y proteger tus Puntos de Vida a medida que te acercas a dibujar a tu Bestia Divina. La propia habilidad del Obelisco puede aplastar a los monstruos de tu oponente de una vez, pero tira la nueva Carta Mágica, Puño del Destino, y puedes negar el efecto de un monstruo y destruirlo sin necesidad de Tributar. Activa durante tu propia fase principal y también puedes aplastar todos los hechizos y trampas de tu oponente. Cada mazo de dios egipcio tiene 40 cartas en total e incluye 1 carta de Dios egipcio y 5 cartas nuevas, 4 cartas nuevas únicas, así como 1 copia de Soul Crossing, una nueva carta de hechizos de juego rápido incluida en ambos mazos que te permite invocar tu carta de Dios Egipcio por Sacrificando tu opinión.",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto8.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto8.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio2.jpg"),
            require("../dataBase/images/accesories/accesorio3.jpg"),
            require("../dataBase/images/accesories/accesorio4.jpg"),
            require("../dataBase/images/accesories/accesorio5.jpg"),
            require("../dataBase/images/accesories/accesorio6.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 8,
        category: "product",
        productName: "Konami YU-GI-OH CCG: DUELISTAS LEGENDARIOS BOOSTER: SOULBURNING VOLCANO Booster Box",
        productPrice: 100,
        description: "Yu-Gi-Oh! CCG: Caja de refuerzo: Volcán Ardiente de Almas de Duelistas Legendarios (24CT)",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto9.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto9.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 9,
        category: "product",
        productName: "Yu-Gi-Oh! TCG: Caja de refuerzo de regla de hechizos",
        productPrice: 100,
        description: "Spell Ruler fue el tercer Yu-Gi-Oh! Juego de cartas intercambiables que nunca se ha lanzado. Durante años, solo podías tener en tus manos estos codiciados paquetes como parte de la Colección Legendaria, pero ahora, justo a tiempo para celebrar el 25 aniversario del juego de cartas, ¡están disponibles como un refuerzo independiente! Spell Ruler fue la primera aparición de cartas de hechizos rituales, monstruos rituales y cartas de hechizos de juego rápido como Mystical Space Typhoon. Esta fue la primera aparición de los monstruos Toon World y Toon de Pegasus del primer Yu-Gi-Oh! serie animada, incluyendo el amado Dragón Toon de Ojos Azules! Junto a ellos se encontraban poderosas Cartas Mágicas como Delinquent Duo, Snatch Steal, y Doloroso Choice. Esta impresión contará con tanto Secret Rares del set.",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto10.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto10.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 10,
        category: "product",
        productName: "Konami Yu-Gi-Oh! TCG: Pantalla de refuerzo de la batalla del caos",
        productPrice: 100,
        description: "Este set de refuerzo presenta nuevos arquetipos y temas, cada uno con sus propios estilos de juego y estrategias únicas. Ya sea que prefieras convocar dragones poderosos, comandar demonios siniestros o desatar fuerzas elementales, Battle of Chaos tiene algo para cada duelista. Con más de 100 cartas para coleccionar, incluyendo cartas raras y secretas, la emoción de descubrir adiciones raras y poderosas a tu mazo está garantizada.",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto11.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto11.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 11,
        category: "product",
        productName: "Yu-Gi-Oh! TCG: Battles of Legend: Crystal Revenge Booster Box",
        productPrice: 100,
        description: "¡Acelera de nuevo y entra en el Nexo Duelista con este set de refuerzo central de veranos! Lleva tus estrategias de Invocación de Sincronía a un universo completamente nuevo de velocidad con nuevas cartas inspiradas en YuGiOh! 5D, incluido el poderoso Dragón Carmesí de la serie de anime, ahora traído a la vida como un verdadero monstruo de sincronización! ¡Asegúrate de recoger Assault Synchron de Battles of Legend: Monstrous Revenge para que puedas empezar a rodar esta estrategia de alta velocidad! ¡Los caballeros de verano calientes regresan! Tres años después de la primera",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/products/producto12.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/products/producto12.jpg"),
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 12,
        category: "accessory",
        productName: "Carpeta",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:true,
        ofPorcentage:18,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio8.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 13,
        category: "accessory",
        productName: "Tapete",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio2.jpg"),
        isAviable: false,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 14,
        category: "accessory",
        productName: "Tapete",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio3.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 14,
        category: "accessory",
        productName: "Tapete",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio4.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 14,
        category: "accessory",
        productName: "Tapete",
        productPrice: 150,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio5.jpg"),
        isAviable: true,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    {
        id: 15,
        category: "accessory",
        productName: "Fundas",
        productPrice: 20,
        description: "¡Vuelven las tarjetas raras de oro premium! Las magníficas raras de oro premium vuelven para dar a muchas de tus tarjetas favoritas un nuevo aspecto con clase. Las tarjetas raras doradas premium han elevado contornos dorados (bordes - símbolos - e iconos que acentúan la obra de arte y añadir textura a muchas de tus tarjetas favoritas).",
        isOff:false,
        ofPorcentage:10,
        productImage: require("../dataBase/images/accesories/accesorio7.jpg"),
        isAviable: false,
        productImageList:[
            require("../dataBase/images/accesories/accesorio1.jpg"),
            require("../dataBase/images/accesories/accesorio7.jpg"),
            require("../dataBase/images/accesories/accesorio8.jpg"),
        ]
    },
    
]